[pytest]
testpaths = tests
norecursedirs =
    kaggle_outputs
    kaggle_project_dataset
    kaggle_debug_kernel
    kaggle_baseline_unet_kernel
    kaggle_high_accuracy_kernel
    outputs
    checkpoints
